# Generated by Django 5.0.2 on 2024-02-18 19:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=64)),
                ('miembro', models.ManyToManyField(blank=True, related_name='grupos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
