# Generated by Django 5.0.2 on 2024-02-18 20:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_grupo'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo',
            name='creador',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='grupos_creados', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
