# Generated by Django 5.0.2 on 2024-02-22 23:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_grupo_creador'),
    ]

    operations = [
        migrations.CreateModel(
            name='Archivos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=64)),
                ('archivo', models.FileField(upload_to='media')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos_de_grupo', to='auctions.grupo')),
                ('publicador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos_de_usuario', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
