# Generated by Django 5.0.2 on 2024-02-24 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_archivos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupo',
            name='nombre',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
